# **1. Perkenalan Dataset**

**sumber dataset**: diperoleh melalui kaggle dengan judul "Gender Classification dataset" yang mengklasifikasikan jenis kelamin pengguna dengan segelintir metric

# **2. Import Library**

Pada tahap ini, Anda perlu mengimpor beberapa pustaka (library) Python yang dibutuhkan untuk analisis data dan pembangunan model machine learning atau deep learning.

In [1]:
# Data manipulation
import pandas as pd
import numpy as np
# Visualization
import matplotlib.pyplot as plt
import seaborn as sns
# Preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
# Model
from sklearn.ensemble import RandomForestClassifier
# Evaluation
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_auc_score, roc_curve

# **3. Memuat Dataset**

Pada tahap ini, Anda perlu memuat dataset ke dalam notebook. Jika dataset dalam format CSV, Anda bisa menggunakan pustaka pandas untuk membacanya. Pastikan untuk mengecek beberapa baris awal dataset untuk memahami strukturnya dan memastikan data telah dimuat dengan benar.

Jika dataset berada di Google Drive, pastikan Anda menghubungkan Google Drive ke Colab terlebih dahulu. Setelah dataset berhasil dimuat, langkah berikutnya adalah memeriksa kesesuaian data dan siap untuk dianalisis lebih lanjut.

Jika dataset berupa unstructured data, silakan sesuaikan dengan format seperti kelas Machine Learning Pengembangan atau Machine Learning Terapan

In [3]:
# Download kaggle dataset

!chmod 600 kaggle.json
!kaggle datasets download -d elakiricoder/gender-classification-dataset

!unzip gender-classification-dataset.zip 'gender_classification_v7.csv'

chmod: cannot access 'kaggle.json': No such file or directory
Dataset URL: https://www.kaggle.com/datasets/elakiricoder/gender-classification-dataset
License(s): CC0-1.0
gender-classification-dataset.zip: Skipping, found more recently modified local copy (use --force to force download)
Archive:  gender-classification-dataset.zip
  inflating: gender_classification_v7.csv

In [4]:
# Load dataset
df = pd.read_csv('/content/gender_classification_v7.csv')
# Tampilkan data awal
df.head()

,long_hair,forehead_width_cm,forehead_height_cm,nose_wide,nose_long,lips_thin,distance_nose_to_lip_long,gender
0,1,11.8,6.1,1,0,1,1,Male
1,0,14.0,5.4,0,0,1,0,Female
2,0,11.8,6.3,1,1,1,1,Male
3,0,14.4,6.1,0,1,1,1,Male
4,1,13.5,5.9,0,0,0,0,Female

# **4. Exploratory Data Analysis (EDA)**

Pada tahap ini, Anda akan melakukan **Exploratory Data Analysis (EDA)** untuk memahami karakteristik dataset.

Tujuan dari EDA adalah untuk memperoleh wawasan awal yang mendalam mengenai data dan menentukan langkah selanjutnya dalam analisis atau pemodelan.

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5001 entries, 0 to 5000
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   long_hair                  5001 non-null   int64
 1   forehead_width_cm          5001 non-null   float64
 2   forehead_height_cm         5001 non-null   float64
 3   nose_wide                  5001 non-null   int64
 4   nose_long                  5001 non-null   int64
 5   lips_thin                  5001 non-null   int64
 6   distance_nose_to_lip_long  5001 non-null   int64
 7   gender                     5001 non-null   object
dtypes: float64(2), int64(5), object(1)
memory usage: 312.7+ KB

ada 2 kolom kontinu yaitu forehead_width dan forehead height yang mengukur panjang dan lebar dahi

disertai dengan beberapa metric yang terdiri dari 0 dan 1 yang menyatakan pengukuran positif ataupun negatif dari adanya rambut panjang/tidak, hidung yang lebar/tidak, hidung yang panjang/tidak, dll

In [6]:
desc = df.describe()
display(desc)

print("\nInsight otomatis:")
for col in desc.columns:
    print(f"Column {col}: mean={desc[col]['mean']:.2f}, std={desc[col]['std']:.2f}")

,long_hair,forehead_width_cm,forehead_height_cm,nose_wide,nose_long,lips_thin,distance_nose_to_lip_long
count,5001.000000,5001.000000,5001.000000,5001.000000,5001.000000,5001.000000,5001.000000
mean,0.869626,13.181484,5.946311,0.493901,0.507898,0.493101,0.498900
std,0.336748,1.107128,0.541268,0.500013,0.499988,0.500002,0.500049
min,0.000000,11.400000,5.100000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,12.200000,5.500000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,13.100000,5.900000,0.000000,1.000000,0.000000,0.000000
75%,1.000000,14.000000,6.400000,1.000000,1.000000,1.000000,1.000000
max,1.000000,15.500000,7.100000,1.000000,1.000000,1.000000,1.000000

Insight otomatis:
Column long_hair: mean=0.87, std=0.34
Column forehead_width_cm: mean=13.18, std=1.11
Column forehead_height_cm: mean=5.95, std=0.54
Column nose_wide: mean=0.49, std=0.50
Column nose_long: mean=0.51, std=0.50
Column lips_thin: mean=0.49, std=0.50
Column distance_nose_to_lip_long: mean=0.50, std=0.50

penjelasan metric

**metric int:**
* long_hair: panjang atau tidaknya rambut (0: pendek, 1: panjang)
* nose_wide: apakah hidung lebar/tidak (0: tidak, 1:lebar)
* nose_long: apakah hidung panjang/tidak (0:tidak, 1:lebar)
* lips_thin: apakah bibir tipis/tidak (0: tidak tipis, 1: tipis)
* distance_nose_to_lip_long: apakah jarak hidung dari bibir panjang (0:tidak, 1:iya)

**fitur float**
* forehead_height_cm: panjang dahi dalam centimeter
* forehead_width_cm: lebar dahi dalam centimeter

# **5. Data Preprocessing**

Pada tahap ini, data preprocessing adalah langkah penting untuk memastikan kualitas data sebelum digunakan dalam model machine learning.

Jika Anda menggunakan data teks, data mentah sering kali mengandung nilai kosong, duplikasi, atau rentang nilai yang tidak konsisten, yang dapat memengaruhi kinerja model. Oleh karena itu, proses ini bertujuan untuk membersihkan dan mempersiapkan data agar analisis berjalan optimal.

Berikut adalah tahapan-tahapan yang bisa dilakukan, tetapi **tidak terbatas** pada:
1. Menghapus atau Menangani Data Kosong (Missing Values)
2. Menghapus Data Duplikat
3. Normalisasi atau Standarisasi Fitur
4. Deteksi dan Penanganan Outlier
5. Encoding Data Kategorikal
6. Binning (Pengelompokan Data)

Cukup sesuaikan dengan karakteristik data yang kamu gunakan yah. Khususnya ketika kami menggunakan data tidak terstruktur.

In [7]:
# Cek Missing Value
print("=== Missing Value ===")
print(df.isnull().sum())

=== Missing Value ===
long_hair                    0
forehead_width_cm            0
forehead_height_cm           0
nose_wide                    0
nose_long                    0
lips_thin                    0
distance_nose_to_lip_long    0
gender                       0
dtype: int64

In [8]:
# Cek Duplikasi
print("\n=== Jumlah Duplikasi ===")
print(df.duplicated().sum())

=== Jumlah Duplikasi ===
1768

In [9]:
# Drop Duplikasi
df = df.drop_duplicates()
# Cek ulang
print("\n=== Jumlah Data Setelah Drop Duplikasi ===")
print(df.shape)

=== Jumlah Data Setelah Drop Duplikasi ===
(3233, 8)

In [11]:
X = df.drop('gender', axis=1)
y = df['gender']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled,
                                                    y,
                                                    test_size=0.2,
                                                    random_state=42)